#!/usr/bin/env bun

/**
 * Memory Index Updater
 * Automatically updates memory/MEMORY.md with entries from memory/YYYY-MM-DD.md
 */

import path from "node:path";
import { readdirSync, readFileSync } from "node:fs";

const scriptDir = path.dirname(import.meta.path);
const projectRoot = path.resolve(scriptDir, "..");

interface MemoryEntry {
  date: string;
  file: string;
  summary: string;
}

async function main(): Promise<void> {
  console.log("📝 Updating memory index...\n");

  const entries = await scanMemoryFiles();

  if (entries.length === 0) {
    console.log("No memory files found");
    return;
  }

  const indexContent = generateIndexContent(entries);
  const indexPath = path.join(projectRoot, "memory", "MEMORY.md");
  await Bun.write(indexPath, indexContent);

  console.log(`✅ Updated memory/MEMORY.md with ${entries.length} entries`);
}

async function scanMemoryFiles(): Promise<MemoryEntry[]> {
  const entries: MemoryEntry[] = [];

  // Use native filesystem API for cross-platform compatibility
  const memoryPath = path.join(projectRoot, "memory");

  const files = readdirSync(memoryPath, { withFileTypes: true });

  for (const file of files) {
    if (!file.isFile()) continue;
    if (!file.name.endsWith(".md")) continue;
    if (file.name === "MEMORY.md") continue;

    const filePath = path.join(memoryPath, file.name);
    const content = readFileSync(filePath, "utf-8");
    const summary = extractSummary(content);

    const match = file.name.match(/^(\d{4}-\d{2}-\d{2})\.md$/);
    if (match) {
      entries.push({
        date: match[1],
        file: file.name,
        summary
      });
    }
  }

  return entries.sort((a, b) => b.date.localeCompare(a.date));
}

function extractSummary(content: string): string {
  // Look for first heading or first substantial line
  const lines = content.split("\n");

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith("# ")) {
      return trimmed.replace("# ", "");
    }
    if (trimmed.length > 10 && !trimmed.startsWith(">")) {
      return trimmed.substring(0, 60) + (trimmed.length > 60 ? "..." : "");
    }
  }

  return "No summary available";
}

function generateIndexContent(entries: MemoryEntry[]): string {
  let content = "# Memory Index\n\n";
  content += "| Date | Summary |\n";
  content += "|------|---------|\n";

  for (const entry of entries) {
    const link = `[${entry.date}](${entry.file})`;
    const summary = entry.summary.replace(/\|/g, "\\|");
    content += `| ${link} | ${summary} |\n`;
  }

  content += "\n<!-- Auto-generated by scripts/update-memory-index.ts -->\n";

  return content;
}

main();
